# Generated by Django 5.1.7 on 2025-04-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividade_app_JWT', '0002_alter_pessoa_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='qte_animais',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
